---
language: python
services: docker

env:
  global:
    - ROLE_NAME: pip
  matrix:
    - >
      CONTAINER_DISTRO=centos
      CONTAINER_VERSION=7
      CONTAINER_COMMAND="/usr/sbin/init"

install:
  # Install test dependencies.
  - pip install molecule[docker]

before_script: []

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
