---
# tasks file for pip

- name: assert supported distributions and versions
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version >= '7' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version >= "7" )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version == "31" )
        ) or
        ( ansible_distribution == "Debian" and ( ansible_distribution_major_version == "10" )
        ) or
        ( ansible_distribution == "Ubuntu" and ( ansible_distribution_major_version == "18" )
        )

- include_tasks: pip.yml
